apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: suntech
  name: node-hello-app
  labels:
    app: node-hello-app
spec:
  selector:
    matchLabels:
      app: node-hello-app
  replicas: 2
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: node-hello-app
    spec:
      containers:
      - name: node-hello-app
        image: jokerdab/diogo-node-hello-app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: suntech
  name: node-hello-app
  labels:
    app: node-hello-app
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: node-hello-app